// same as src/utils/css-class.scss
export const enum CssClass {
  SELECTING = "selecting",
  SELECTED = "selected",
  PANIC = "panic",
  NEXT = "next",
  HAS_WAITING_PERSON = "has_waiting_person",
  SCARED = "scared",
  SCARY = "scary",
  AFFECTED_BY = "affected_by",
  SECONDARY_AFFECTED_BY = "secondary_affected_by",
  T13A = "t13a",
  P_T13A = "p_t13a",
  HAS_PERSON = "has_person",
  HAS_LEFT = "has_left",
  HAS_RIGHT = "has_right",
  CELL = "cell",
  IS_DRAGGING = "is_dragging",
  IS_DRAGGED = "is_dragged",

  // arrows
  UP = "up",
  DOWN = "down",
  LEFT = "left",
  RIGHT = "right",
  AUTO = "auto",
  ARROW = "arrow",

  // help
  HELP = "help",
  WELCOME = "welcome",
  STATS = "stats",
  STATS_GRID = "stats_grid",
  STAT = "stat",
  GOOD = "good",
  BAD = "bad",

  TABLE = "table",
  FIRST = "first",
  PLATE = "plate",
  CHAIR = "chair",
  PERSON = "person",
  EMOJI = "emoji",
  FIELD = "field",
  WON = "won",
  START_BUTTON = "start_button",
}
